# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
#import os
#import sys
#sys.path.append("sphinx-configuration.py")
import yaml

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinxcontrib.confluencebuilder',
    'myst_parser'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'pt-BR'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extensions than .md to process as Markdown or reStructuredText compatible text
source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown',
}

confluence_ask_user = False
confluence_ask_password = False
confluence_page_hierarchy = True

master_doc = "README"

# Import Code from YAML Configuration
sphinx_extended_configuration = yaml.load(open('sphinx-configuration.yaml','r'), Loader=yaml.FullLoader)

project = sphinx_extended_configuration["sphinx"]["project"]["name"]
copyright = sphinx_extended_configuration["sphinx"]["project"]["copyright"]
author = sphinx_extended_configuration["sphinx"]["project"]["author"]

# -- Confluence Options ------------------------------------------------------
confluence_publish = sphinx_extended_configuration["sphinx"]["confluence"]["publish"]
confluence_space_name = sphinx_extended_configuration["sphinx"]["confluence"]["space"]["name"]
confluence_server_url =  sphinx_extended_configuration["sphinx"]["confluence"]["url"]
confluence_parent_page = sphinx_extended_configuration["sphinx"]["confluence"]["parent_page"]